### ISSUE TITLE
TSlint

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#10]
We want to add this when its ready

https://github.com/fuse-box/fuse-box/issues/146

**Comment by vegarringdal** [comment]
@arjendeblok 

Should we add this one ?
https://github.com/fuse-box/fuse-box-typechecker

Nice to have..

**Comment by arjendeblok** [comment]
@vegarringdal  Looks good at first. Have not tested it yet, but I will do that this weekend.

**Comment by vegarringdal** [comment]
It can get better,  I might change it just show the error for the edited file after first run, or add it as a option, maybe option to pass in TS codes you dont want it to show.

**Comment by vegarringdal** [comment]
@arjendeblok updated it so the types checking runs in own thread, was kinda annoying how it blocked everything

**Comment by vegarringdal** [comment]
@arjendeblok 
I updated the tsconfig with module "commonjs"
@nchanged changed it, and just got a issue on the loader complaining about it not working.

@arjendeblok 
Great if you have time to give the seed a small update, atm it takes forever to run it(25-30sec) with version 1.3.124, prob sourcemaps on modules

**Comment by arjendeblok** [comment]
@vegarringdal  I am busy getting the source maps to work. If I get this I will update the seed with it, without the default option for vendor files. Now the SourceMapPlainJsPlugin generates source maps in the latest version for all files (including vendor files), which it did not before. So I will remove that one. 
See fuse-box issue 310 on the discussion/progress on this.

**Comment by arjendeblok** [comment]
@vegarringdal I did an update on fuse-box and version 3.1.124 did not work anymore with the aurelia seed. 3.1.123 works fine. Do you have the same issue with your sample code?

**Comment by vegarringdal** [comment]
@arjendeblok @nchanged  pushed out v 125, you just need to update to that one or edit the tsconfig file with module to "commonjs" if you want to stay on v124

**Comment by arjendeblok** [comment]
@vegarringdal @nchanged tried to get v125, but npm gives an error that is misses a file `bin\fsbx.,js`

**Comment by vegarringdal** [comment]
@arjendeblokk, Ive only teste v124 so I dont know, not at the computer, but the v124 worked on the seed when I updated the tsconfig file from amd module to commonjs module

**Comment by arjendeblok** [comment]
@vegarringdal I created a pull request that solved the issue with the source maps.
Vendor files are off and caching is on. See #18

**Comment by arjendeblok** [comment]
@vegarringdal v126 does work ok. Updated aurelia seed with it.

**Comment by vegarringdal** [comment]
@arjendeblok Great, merged :-)

**Comment by vegarringdal** [comment]
closing, since old seed is replaced and updated to fusebox 2.0
