### ISSUE TITLE
users.ts

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#11]
@arjendeblok 

Why not keep it as possible to original ?
Any special reasons?

fusebox-seed:
```
import {lazy} from 'aurelia-framework';
import {HttpClient} from 'aurelia-fetch-client';

// polyfill fetch client conditionally
const fetch = !self.fetch ? System.import('isomorphic-fetch') : Promise.resolve(self.fetch);

interface IUser {
  avatar_url: string;
  login: string;
  html_url: string;
}

export class Users {
  heading: string = 'Github Users';
  users: Array<IUser> = [];
  http: HttpClient;

  constructor(@lazy(HttpClient) private getHttpClient: () => HttpClient) {}

  async activate(): Promise<void> {
    // ensure fetch is polyfilled before we create the http client
    await fetch;
    const http = this.http = this.getHttpClient();

    http.configure(config => {
      config
        .useStandardConfiguration()
        .withBaseUrl('https://api.github.com/');
    });

    const response = await http.fetch('users');
    this.users = await response.json();
  }
}
```

Original:
```
import {autoinject} from 'aurelia-framework';
import {HttpClient} from 'aurelia-fetch-client';
import 'fetch';

@autoinject
export class Users {
  public heading = 'Github Users';
  public users = [];

  constructor(private http: HttpClient) {
    http.configure(config => {
      config
        .useStandardConfiguration()
        .withBaseUrl('https://api.github.com/');
    });
  }

  public activate() {
    return this.http.fetch('users')
      .then(response => response.json())
      .then(users => this.users = users as any);
  }
}
```

Original works fine in ie11 too
https://vegarringdal.github.io/aurelia-fusebox-test/

**Comment by arjendeblok** [comment]
Where did you get that 'original' then.

Mine is from https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack/src/users.ts 

When using typescript the idea is to use the async/await pattern.

**Comment by arjendeblok** [comment]
There is also a bug in there. `System.Import` should be `require` to be able to run in IE11.

**Comment by vegarringdal** [comment]
At the skeleton-typescript 😄 
https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript/src/users.ts

**Comment by vegarringdal** [comment]
Actually when testing newest fuse on my test repo it somehow breaks and loader fails somehow.
Are you having issues like this on v 121 ? but 117 works

@nchanged 
Have you done anything on fuse how it bundles some parts lately ?

**Comment by vegarringdal** [comment]
From what I can tell it happens in v118, user.html is missing locals function

**Comment by vegarringdal** [comment]
@nchanged 
never mind, must be something Im doing, this seed works fine

Ill do more testing and try and figure out why my is breaking after v118, I have the routes in own folder, maybe that is what breaks it, also bundle is in folder

**Comment by vegarringdal** [comment]
@arjendeblok 

Found my bug in the end, for some reason having variable "http" in constructor failed. Nice to know about incase you copy code from one of the other skeletons :-)

Now Ive updated this to use async await too:
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/src/routes/users.ts#L19-L21

https://vegarringdal.github.io/aurelia-fusebox-test/

**Comment by arjendeblok** [comment]
I think that the issue was that you designated the method as async and did not use await.
If you did not set async in the method then you can use the old promises way with .then()

**Comment by vegarringdal** [comment]
No the "http" issue was a fusebox bug, got fixed in 122.preview4, there had been a similar with "https" so @nchange knew what to do.

**Comment by nchanged** [comment]
yeah it's all fixed in `122-preview.4`
