### ISSUE TITLE
IE 11 Performance

### ISSUE THREAD

**Issue by arjendeblok** [fuse-box/fuse-box-aurelia-seed#12]
Current version is very slow on IE 11. It takes more than 6 seconds to load.
Chrome does it less than a second.

The difference is that IE 11 needs a Promise polyfill, but Chrome does not. In this example bluebirdjs is used as a polyfill.

There is a known problem in bluebirdjs when a lot of exceptions are thrown. Bluebird as a default tries to get long stack traces when an exception is thrown in a problem. This takes some time and if a lot of exceptions are thrown (which are catched by the way) then this takes a lot of performance.

**Comment by arjendeblok** [comment]
Created pull request PR13 for performance issue.
When EnableLogStackTraces of bluebird is set to false then load speed takes less than a second in IE 11.

**Comment by vegarringdal** [comment]
@arjendeblok Great, merged

Any chance you could include the bundle (put in own dir) so I can active GH pages too.
We should also add reference to skeleton where we copied sample from.
