### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#17]
@arjendeblok 

Maybe we could put this is the readme ?
https://fuse-box.github.io/fuse-box-aurelia-seed

On the suggestion PR I added github star, incase someone opens the demo its really easy to go back and star it 👍 
Or didnt like that one ?

You can see it here.. can upload images, think github is having server issues
https://vegarringdal.github.io/fuse-box-aurelia-seed/

**Comment by nchanged** [comment]
@vegarringdal Absolutely stunning! Thank you so much for making it! You think it's ready for aurelia to actually try it? ;-)

**Comment by nchanged** [comment]
Let's put a star button there, of course!

**Comment by nchanged** [comment]
@vegarringdal one thing, you guys did not manage to make HMR work there?

**Comment by arjendeblok** [comment]
Of course we should put this in the readme. Very nice. And include a star button also.

**Comment by vegarringdal** [comment]
@nchanged 
Ive incuded the HMR code to @arjendeblok  in the PR Ive made on my loader rebuild.
It have misc option for if you want to use the HMR with aurelia-hot-reload or just reload page when changes happen.
Was thinking people could use the vaibles with the ENV plugin, so its not active in production etc.

"aurelia-hot-reload" is really cool, but not everything you can change, but it might get better as the aurelia team make this one better:
https://github.com/aurelia/hot-module-reload
, I personally like the reload all..

**Comment by vegarringdal** [comment]
closing, since old seed is replaced and updated to fusebox 2.0
