### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#21]
@Thanood We need to look at fonts, atm I just included them
New docs might have something on how to make this better
@nchanged can we include fonts in ```fuse.register``` that would have been useful to have a kinds of files here, if that is possible

**Comment by nchanged** [comment]
Hm, need to check how that will work

**Comment by Thanood** [comment]
In this case, the fonts must somehow be relative to the Materialize css virtual path. I dont't know right now if/how this is possible. 😃 

I think it would be enough if we copied them into the root folder - because the bundle is in `/dist` and so fonts would be one level up (`../fonts`). Right?

**Comment by nchanged** [comment]
Oh guys, why not using [Sparky](http://fuse-box.org/page/sparky)

**Comment by vegarringdal** [comment]
no, root will be where the index.html is. (i think)

**Comment by nchanged** [comment]
@vegarringdal you can apply some magic there =) FuseBox is about magic after all =)

**Comment by vegarringdal** [comment]
maybe, I will need to read up how it works, somethink for the next days :-)

**Comment by nchanged** [comment]
@vegarringdal it's like gulp but on steroids ;-)

**Comment by Thanood** [comment]
Yeah, should be easy. I've done it before once.. 😏

**Comment by Thanood** [comment]
```js
Sparky.task('copy-fonts', () => {
    Sparky.src('node_modules/materialize-css/dist/fonts/roboto/*.*')
        .file('*.*', file => { console.log(file); })
        .dest('fonts/');
});
```

Any idea why this does nothing? 😂

**Comment by nchanged** [comment]
@Thanood cuz it's not a valid glob
```
node_modules/materialize-css/dist/fonts/roboto/**/**
```

**Comment by nchanged** [comment]
```
 Sparky.src('node_modules/materialize-css/dist/fonts/roboto/**/**')
        .dest('fonts/$name');
```

**Comment by Thanood** [comment]
Really?

```
node_modules/materialize-css/dist/fonts/roboto/**/**
```

Even if there are no subdirectories?

That `$name` seems pretty obvious.. 😏

**Comment by Thanood** [comment]
```
Sparky.src('node_modules/materialize-css/dist/fonts/**/**')
        .dest('fonts/$name');
```

Still nothing.. (even with `roboto`).
Hmmm...

**Comment by nchanged** [comment]
**/**.** :)

**Comment by nchanged** [comment]
Oops the extension is missing

**Comment by Thanood** [comment]
Okay, something is not quite right here. That may as well be my understanding of globs, but anyway.. 😏 
Every resource I find tells me a glob is used/derived from POSIX file patterns. Which makes sense. So f.i. like bash. I'm quite familiar with bash pattern matching and tried every glob I used with my local shell.

```
$ ls node_modules/materialize-css/dist/fonts/** -xlgGo
total 768
-rw-r--r-- 1 90308 Mai 10 09:39 Roboto-Bold.woff
-rw-r--r-- 1 64800 Mai 10 09:39 Roboto-Bold.woff2
-rw-r--r-- 1 89672 Mai 10 09:39 Roboto-Light.woff
-rw-r--r-- 1 64268 Mai 10 09:39 Roboto-Light.woff2
-rw-r--r-- 1 90560 Mai 10 09:39 Roboto-Medium.woff
-rw-r--r-- 1 65412 Mai 10 09:39 Roboto-Medium.woff2
-rw-r--r-- 1 89828 Mai 10 09:39 Roboto-Regular.woff
-rw-r--r-- 1 64832 Mai 10 09:39 Roboto-Regular.woff2
-rw-r--r-- 1 88132 Mai 10 09:39 Roboto-Thin.woff
-rw-r--r-- 1 63056 Mai 10 09:39 Roboto-Thin.woff2
```

So `node_modules/materialize-css/dist/fonts/**` should be a valid glob right? No `/**/**` and no extension. 😃 

Tell me what's wrong. Or maybe I'm doing something else wrong...

**Comment by nchanged** [comment]
@Thanood that one is valid
`node_modules/materialize-css/dist/fonts/**/**.**`

**Comment by vegarringdal** [comment]
With path:
`https://fuse-box.github.io/fuse-box-aurelia-seed/#/`

these font paths will be a problem on the github live sample, also looks like we need to include a new build for the live demo, since hmr is active and tries to connect

![image](https://cloud.githubusercontent.com/assets/2901416/25954093/861ee0be-3665-11e7-8ee2-3a106600b3b8.png)
![image](https://cloud.githubusercontent.com/assets/2901416/25954104/91316864-3665-11e7-9b99-93f9e1cc4f56.png)

**Comment by Thanood** [comment]
I can't remember changing the fonts path (or rather uploading my local change).. Did I? 😮

**Comment by vegarringdal** [comment]
no, its just when running it localy we are at the base of the server path... when github repo we are under the repo name, so unsure how the css file gets it paths, because I guess its relative to that  (Im no font expert or css...)

**Comment by Thanood** [comment]
@vegarringdal I can't find the issue where you suggested to just copy css and fonts and load from a link tag. Good idea. 😃 

Can you try it? My "copy-fonts" task still trolls me and doesn't copy anything.

**Comment by vegarringdal** [comment]
> I can't find the issue where you suggested to just copy css and fonts and load from a link tag. Good idea

Was in gitter I think :-)

**Comment by vegarringdal** [comment]
@Thanood u forgot the "return"
```
Sparky.task('copy-fonts', () => {
    return Sparky.src('node_modules/materialize-css/dist/fonts/**/**.*')
        .clean("fonts/")
        .dest('fonts/');
});
```

**Comment by Thanood** [comment]
🤦‍♂️ <-- facepalm (to myself of course)

**Comment by vegarringdal** [comment]
:-) been there, done that, and will do it soon :-)

**Comment by vegarringdal** [comment]
@nchanged @devmondo 
I need some spark help, because either its bugged, or Im making it bug.. :-)

---

* 1

I want to copy the css and font

![image](https://cloud.githubusercontent.com/assets/2901416/26002011/8a355196-372e-11e7-9810-ae3350cb8547.png)

---

* 2

I have this I run in sequence ```node fuse dev```

```javascript
Sparky.task('copy-fonts', () => {
    return Sparky.src('./node_modules/materialize-css/dist/fonts/**/*.*')
        
        .dest('styles/materialize-css/fonts/');
});


Sparky.task('copy-css', () => {
    return Sparky.src('./node_modules/materialize-css/dist/css/*.*')
        .dest('styles/materialize-css/css/');
});


// "run" is the bundle etc...just overlook it for now
Sparky.task("dev", ["copy-fonts", "copy-css", "run"], () => {
  
});
```

----

* 3

why is the entire is the parent folders (red arrows) included.?? that is so weird

![image](https://cloud.githubusercontent.com/assets/2901416/26002224/46b4ea52-372f-11e7-89aa-12be535c0513.png)

**Comment by nchanged** [comment]
[here](http://fuse-box.org/page/sparky#source)
`Sparky.src("./assets/*.png", { base: './src' }).dest('./dist')`

**Comment by vegarringdal** [comment]
looks like this works..
but it feels really weird 

```
Sparky.task('copy-fonts', () => {
    return Sparky.src('**/*.*', { base: 'node_modules/materialize-css/dist/fonts/' })
        .clean('styles/materialize-css/fonts/')
        .dest('styles/materialize-css/fonts');
});
```

**Comment by vegarringdal** [comment]
now we dont have any errors in liv demo with fonts or hmr if w run ```npm run demo``` before pushing, need to create a on folder for dev runs and production, but first need to figure out something smart with the index.html, but we can create own issue for that

See demo link:
https://fuse-box.github.io/fuse-box-aurelia-seed/

no more errors..

![image](https://cloud.githubusercontent.com/assets/2901416/26005589/d9de774e-3739-11e7-8713-b62b44a9ffbe.png)

**Comment by devmondo** [comment]
perfecto!!!!
