### ISSUE TITLE
some ideas for improvement

### ISSUE THREAD

**Issue by Thanood** [fuse-box/fuse-box-aurelia-seed#23]
Waves (ripples) seem to be initialized twice so "waved" buttons stay dimmed after clicking. Annoying.
Any idea why there is no Aurelia debug log although it's activated?

I'll have a look at the waves and fonts (#21) tomorrow.

**Comment by vegarringdal** [comment]
>Waves (ripples) seem to be initialized twice so "waved" buttons stay dimmed after clicking. Annoying.
Any idea why there is no Aurelia debug log although it's activated?

hmm, yes you are right, that is weird, prb some copy paste error I did yesterday :-)
Kinda rushed in the end since fusebox 2.0 was about to get released, and @nchanged really wanted the old one replaced :-)

**Comment by vegarringdal** [comment]
wave buttons are fixed now with you latest PR
https://fuse-box.github.io/fuse-box-aurelia-seed/#/

Need to figure out why the logging is failing

**Comment by vegarringdal** [comment]
![image](https://cloud.githubusercontent.com/assets/2901416/25958334/a5c73bd6-3670-11e7-85d9-2c0b7d587a15.png)

@Thanood 

hehe, its working, its just hidden by chrome in the latest updates

![image](https://cloud.githubusercontent.com/assets/2901416/25958277/8525bdf8-3670-11e7-8d47-2d8b502aac19.png)

**Comment by Thanood** [comment]
Oh! Good to know.  :smiley:
