### ISSUE TITLE
Doesn't run with latest version of fuse-box or materialize

### ISSUE THREAD

**Issue by erikvullings** [fuse-box/fuse-box-aurelia-seed#29]
I've checked out your project, did a yarn install, and tried to run it. Unfortunately, the project had several issues:
- The typecheck plugin isn't working anymore, so I've removed it from `fuse.js`
- The following problem is probably related to the `materialize-bridge` (when I don't register the bridge, fuse-box runs just fine, but I get an error in the console (`md-well.html` cannot be found):

```console
yarn start v0.24.6                                                                                                                            
$ node ./build/fuse dev                                                                                                                       
 Launch "dev"                                                                                                                                 
  Resolve "copy-fonts"                                                                                                                        
 Launch "copy-fonts"                                                                                                                          
→Copy to ../styles/materialize-css/fonts                                                                                                      
→Copy to ../styles/materialize-css/fonts                                                                                                      
  Resolve "copy-css"                                                                                                                          
 Launch "copy-css"                                                                                                                            
→Copy to ../styles/materialize-css/css                                                                                                        
→Copy to ../styles/materialize-css/css                                                                                                        
vendor ->                                                                                                                                     
app ->                                                                                                                                        
TypeError: Cannot read property 'entryFile' of undefined                                                                                      
    at Function.onNode (C:\dev\temp\fuse-box-aurelia-seed-master\node_modules\fuse-box\dist\commonjs\analysis\plugins\OwnBundle.js:13:28)     
    at plugins.forEach.plugin (C:\dev\temp\fuse-box-aurelia-seed-master\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:80)   
```
I'm running node v8 (but I've also tried it on node v7) and fuse-box v2.1.0

**Comment by nchanged** [comment]
oh yeah, you need to update to the latest beta (upcoming release)
`2.2.0-beta.25` it's fixed there

**Comment by vegarringdal** [comment]
and I need to update the seed, since Ive also updated the typechecker this week, but been holding if for the 2.2, so that one you just need to remove (or updated)
Plan is to update the seed this weekend

**Comment by erikvullings** [comment]
@nchanged thanks for the suggestion: however, that doesn't fix everything yet. Indeed, I can run fuse-box just fine, but in the browser, nothing is shown expect the following console error:
```console
Package not found fuse-box-css
```
Any suggestions? Do I need to install that too?

**Comment by nchanged** [comment]
Oh, yeah, that's a very interesting bug. Could you add `+fuse-box-css` to instructions? I was trying to fix it the other day, now I know where I can reproduce it =)

**Comment by vegarringdal** [comment]
@nchanged Just as info, I think that bug is only when updating and you have not removed the .fusebox folder, because I had it for a little while, and suddenly is was gone.
Do you save the fusebox version in the .fusebox folder?

**Comment by vegarringdal** [comment]
@erikvullings 
Sorry for the horrible start on the seed.

**Comment by erikvullings** [comment]
@nchanged Yep, that solved the problem. So to summarize for others:
Remove the typechecker in `fuse.js`, add the `+ fuse-box-css` to your app, and:
```console
yarn remove fuse-box
yarn add fuse-box@2.2.0-beta.25
```

THANKS for your help!

**Comment by vegarringdal** [comment]
@erikvullings 

Updated the seed so its set with the beta, and updated build to use newest typechecker

**Comment by erikvullings** [comment]
@vegarringdal 
Nice work, I've just checked it and everything works again. Thanks for the quick response.
(BTW while following the link to fuse-box, its favicon is missing - http://fuse-box.org:3333/favicon.ico)

**Comment by vegarringdal** [comment]
@erikvullings 
>Nice work, I've just checked it and everything works again. Thanks for the quick response.

Thx

> (BTW while following the link to fuse-box, its favicon is missing - http://fuse-box.org:3333/favicon.ico)

Yes, forgot to add it 😂 , but its not breaking anything and its a easy fix
