### ISSUE TITLE
loading screen

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#3]
Just tried it, if you dont load the styles.css in the index.html the "loading screen" wont work

![image](https://cloud.githubusercontent.com/assets/2901416/23071435/a11dafa8-f52e-11e6-9da3-9ed78a2f8d43.png)

This should be:
![image](https://cloud.githubusercontent.com/assets/2901416/23071503/d5c8dec6-f52e-11e6-903a-34f71a0b4721.png)

**Comment by vegarringdal** [comment]
@arjendeblok
having that styles folder original skeleton got would prb be best here ?

**Comment by nchanged** [comment]
Yes and no :) we need to demonstrate HMR there. If we include just the loader CSS into the head, that would solve the issue!

**Comment by vegarringdal** [comment]
Sure, but if its a big bundle and you ahve a loading screen this isnt a good way to do it, might want to think about smaller bundles then...
Point of the loading screen is to show something during load
We could add some other css that can get imported

**Comment by nchanged** [comment]
@vegarringdal i was referring to the actual _loader_ CSS, probably 2 classes, right?

**Comment by vegarringdal** [comment]
This:
```
.splash {
  text-align: center;
  margin: 10% 0 0 0;
  box-sizing: border-box;
}

.splash .message {
  font-size: 72px;
  line-height: 72px;
  text-shadow: rgba(0, 0, 0, 0.5) 0 0 15px;
  text-transform: uppercase;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.splash .fa-spinner {
  text-align: center;
  display: inline-block;
  font-size: 72px;
  margin-top: 50px;
}

/* animation definitions */
@-webkit-keyframes fadeInRight {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0)
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none
  }
}

@keyframes fadeInRight {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(100%, 0, 0);
    -ms-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0)
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    -ms-transform: none;
    transform: none
  }
}

@-webkit-keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
```
and fontawsome

Would it not be best to have this loading in normal style.css and more the other styling into the app?
Separate app and index..

**Comment by vegarringdal** [comment]
Btw, I do not know much about the "loader CSS" 😂 

So please show us the best way, so much to learn about amazing fusebox 👍

**Comment by nchanged** [comment]
No man, I was talking about aurelia CSS, I put it wrongly, I am sorry. Welcome screen/loading screen. Just put the styles for it,  so it will look nicely. "AURELIA NAVIGATION SKELETON" just enough styles to make it pretty.

**Comment by vegarringdal** [comment]
👍

**Comment by arjendeblok** [comment]
I agree with the solution. I will split the CSS needed for the loader and the rest of the CSS.
And then try to bundle only the rest and include the loader CSS directly in the head.

**Comment by vegarringdal** [comment]
@arjendeblok 👍
