### ISSUE TITLE
We should add a license

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#4]
We should add a license

Official skeleton is, how does that affect us?
https://github.com/aurelia/skeleton-navigation/blob/master/LICENSE
![image](https://cloud.githubusercontent.com/assets/2901416/23071632/51afc00e-f52f-11e6-92aa-40c1a24fa159.png)

**Comment by arjendeblok** [comment]
Can we use the same license? 
If yes then I will add it.

**Comment by vegarringdal** [comment]
@arjendeblok

Not sure, dont know how that license work.
@nchanged need you on this one...

Also think we should have a reference to original skeleton in readme file

**Comment by nchanged** [comment]
@vegarringdal absolutely. Let's put a reference.

**Comment by vegarringdal** [comment]
@nchanged 
You didnt respond on what licence to use to @arjendeblok  :-)

**Comment by arjendeblok** [comment]
@nchanged could we include the same license?
I think that the CC0 license is perfect for seeds/skeletons/sample code.

**Comment by nchanged** [comment]
Of course!
