### ISSUE TITLE
Include bundles and have it in a own folder to we can activate GHpages?

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#6]
Include bundles and have it in a own folder to we can activate GHpages?

@nchanged what do you think?

Would work like this then
https://vegarringdal.github.io/aurelia-fusebox-test/

**Comment by nchanged** [comment]
Absolutely!

**Comment by vegarringdal** [comment]
👍 

Suggestion then:

```/build``` for js build files
```/bundles``` for bundles

This needs to be added to dev server for it to work
```
  + aurelia-templating-router
        `, {
        root: './'
    })
```

**Comment by vegarringdal** [comment]
@arjendeblok 
Could you add this one if you do a merge, if that works we know the app works too :-)

Btw I have this where I was testing a lot: https://github.com/vegarringdal/aurelia-fusebox-test
Plan was to bring a lot into this repo after I had figured how to do all :-) (was not going to bring my datagrid)
Its working in IE11 and sourcemaps under bundle folder etc now

**Comment by vegarringdal** [comment]
@nchanged Can you set the gh-pages to master, @arjendeblok included the bundles now.

**Comment by nchanged** [comment]
@vegarringdal I though you had write access to the repository? ;-)

**Comment by vegarringdal** [comment]
not to setting part

![image](https://cloud.githubusercontent.com/assets/2901416/23367382/56f6dede-fd0a-11e6-9a2d-36cbdaa87206.png)

**Comment by nchanged** [comment]
https://fuse-box.github.io/fuse-box-aurelia-seed/

Look gooooood =)
