### ISSUE TITLE
Add support for IE11?

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-seed#7]
@arjendeblok 

getting ```SCRIPT5009: 'Promise' is undefined```
So bluebird isnt loaded correct, bacause that would have acted like a polyfill for that

Will also need fetch pollyfill for IE11 ```whatwg-fetch``` works

Info:
Got both to work here:
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/src/main.ts

Dunno if Im doing it the best way with bluebird though..

**Comment by nchanged** [comment]
Is it failing on with devServer?

**Comment by vegarringdal** [comment]
problem is just that bluebird isnt loaded and we need fetch polyfill, I got it to work in my test app under my aurelia-fuse-test, Ive added both there:-)

**Comment by arjendeblok** [comment]
Created PR for that.

**Comment by vegarringdal** [comment]
👍 
@arjendeblok small questions regarding some other parts:

Ive never had this and it worked just fine, what does it do really?
https://github.com/fuse-box/fuse-box-aurelia-seed/blob/master/src/main.ts#L20-L22


And why do you have it like this:
```main.js + **/*.js + **/*.ts + **/*.html + **/*.css + **/*.ttf```
https://github.com/fuse-box/fuse-box-aurelia-seed/blob/master/build-app.js#L25

Its a typescript project, so why any of ```main.js``` & ```**/*.js```? something  dont know yet about fusebox? Ive always just had main.ts

**Comment by arjendeblok** [comment]
@vegarringdal  If I look at https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/build/fb-app-build-bundle.js I also see that parts. So to which are you referring to? 
If we can skip this that would be better of course.

**Comment by vegarringdal** [comment]
@arjendeblok , added images 👍 

---

Ive never had this and it worked just fine, what does it do really?
https://github.com/fuse-box/fuse-box-aurelia-seed/blob/master/src/main.ts#L20-L22

You could just include this in the bundle...(might need pal aan a few others)
![image](https://cloud.githubusercontent.com/assets/2901416/23092285/85118138-f5c7-11e6-9ac4-6969adc44747.png)





---

And why do you have it like this:
main.js + **/*.js + **/*.ts + **/*.html + **/*.css + **/*.ttf
https://github.com/fuse-box/fuse-box-aurelia-seed/blob/master/build-app.js#L25

![image](https://cloud.githubusercontent.com/assets/2901416/23092292/b5c0845a-f5c7-11e6-9249-7e89ac2aca79.png)

**Comment by arjendeblok** [comment]
Pal browser can be moved to bundle indeed.
Main.js can be changed to main.ts and *.js and *.ttf can be removed. *.ttf was for trying to get font-awesome packaged with fonts.
